services:
  ghost-db:
    image: mysql:8
    container_name: ghost-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ghost_db_data:/var/lib/mysql

  ghost:
    image: ghost:5-alpine
    container_name: ghost-blog
    restart: unless-stopped
    depends_on:
      - ghost-db
    ports:
      - 2368:2368
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ghost
      database__connection__password: ghostpass
      database__connection__database: ghost
    volumes:
      - ghost_content:/var/lib/ghost/content

volumes:
  ghost_db_data:
  ghost_content:
